version: '3.8'

services:
  dtn-node:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: dtn-node
    environment:
      - NODE_ENV=production
      # Keystore configuration
      - FOUNDRY_KEYSTORE_PASSPHRASE=${FOUNDRY_KEYSTORE_PASSPHRASE}
      - FOUNDRY_KEYSTORE_PATH=/app/keystore
    volumes:
      # Mount config file if needed
      - ./nodeConfig.yaml:/app/nodeConfig.yaml:ro
      # Mount cache directory for persistence
      - dtn-cache:/app/cache
      # Mount keystore directory for key management
      - ./keystore:/app/keystore
    restart: unless-stopped
    # Uncomment if you need to expose ports
    # ports:
    #   - "3000:3000"

volumes:
  dtn-cache: 